services:
  jupyter:
    container_name: metpy_test
    image: metpy_test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/metpy_test:/app
    ports:
      - "${PORT:-8888}:8888"
